

module.exports = {

  CORS: [],

  ISSUE_CLOSED: 'e50bb3cac0f64a83bd092187336478fd',
  ISSUE_EDIT: 'b6d4956054694d3b9db65eda368ebfbd',
  ISSUE_DELETE: '09d6aa3f18154fa89af09c5aa37f9941',
  ISSUE_TRANSFER: '4b486e286d0e4a098e55c51f54cf1204',
  PROJECT_EDIT: `154b6606a95947a19e803cffe6fbc5f5`,
  PROJECT_DELETE: `0b373aa290a54aa4bd4d6612e00bb16a`,

  api: {
    userLogin2: `/wy/login/login`,
    userRegister2: `/wy/login/register`,
    logout2: `/wy/login/logout`,
    userQuery2: `/wy/user/userQuery`,
    userQuery3: `/wy/user/getUserAndMenu`,
    editUser2: `/wy/user/editUser`,
    demandQuery2: `/wy/demand/getDemandList`,
    getDemand: `/wy/demand/getDemand`,
    projectQuery2: `wy/project/findProject`,
    accQuery2: `wy/user/getUserByRoleId?roleId=40042e7dc4404753aabd7473eb879e4a`,
    pmQuery2: `wy/user/getUserByRoleId?roleId=be0816be89b64fcfb69a1c74e13e91a9`,
    addDemand2: `wy/demand/addDemand`,
    updateDemand2: `wy/demand/updateDemand`,
    getDemandListByDevId: `wy/demand/getDemandListByDevId`,
    getDemandListByCreactName: `wy/demand/getDemandListByCreactName`,
    getDemandLog: `wy/demand/getDemandLogById`,
    addDemandLog: `wy/demand/addDemandLog`,
    getUsers: `wy/user/getUsers`,
    demand: `wy/demand`,
    getIssueList: `wy/issue/getIssueList`,
    addIssue2: `wy/issue/addIssue`,
    getIssue: `wy/issue/getIssue`,
    getProject: `wy/project/getProjectList`,
    saveProject: `wy/project/saveProject`,
    deleteProjectById: `wy/project/deleteProjectById`,
    deleteIssueById: `wy/issue/deleteIssueById`,
    closeIssueById: `wy/issue/closeIssueById`,
    issueToDemand2: `wy/issue/issueToDemand`,
    checkUserName: `wy/user/checkUserName`,
    archs: `wy/arch/getArchs`,
    archCreate: `wy/arch/archCreate`,
    archRemove: `wy/arch/archRemove`,
    archUpdate: `wy/arch/archUpdate`,
    peoples: `wy/people/query`,
    createTeam2: `wy/people/createTeam`,
    pickup2: `wy/people/pickup`,
    getout2: `wy/people/getout`,
    dismiss2: `wy/people/dismiss`,
  },
}
